### ISSUE TITLE
Time out sign-ins after N minutes

### ISSUE THREAD

**Issue by veryhappythings** [veryhappythings/discord-gather#3]

**Comment by Doezer** [comment]
Also planned on my fork but I'd be happy to hear any ideas you have on this.
I was thinking about getting the local time and having some kind of job that checks it every x minute to see if the timeout is reached, but I'm guessing it might be easier using asyncio in some way, although I'm not very familiar with it.

**Comment by veryhappythings** [comment]
In a previous bot for IRC I think I had a "last seen" dictionary. Every time a message came in, it updated the last seen time for whoever sent the message. Then a thread ran a function every minute or so that signed out anyone who hadn't been seen in the last 5 minutes.

By using any message to update the last seen dict, you allow people to stay signed in when they're actively chatting.

**Comment by veryhappythings** [comment]
Glad to see this is in use by the way, and please do PR back into the main repo if you can :) I should try to localise the whole thing so that your fork doesn't have to change as much! Please do let me know if you have any issues.

**Comment by veryhappythings** [comment]
The bot now signs people out if they go inactive on Discord - I think that'll do.
